[build]
  publish = "public/"
  command = "./build"
  [build.environment]
    GO_VERSION = "1.16"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[redirects]]
  from = "/advanced"
  to = "/advanced.html"
  status = 301
