[build]
  publish = "public/"
  command = "./build"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[redirects]]
  from = "/advanced"
  to = "/advanced.html"
  status = 301
