[build]
  publish = "public/"
  command = "./build"
  [build.environment]
    GO_VERSION = "1.16"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"

[[redirects]]
  from = "/advanced"
  to = "/advanced.html"
  status = 301
